#ifndef SOLARUS_MAJOR_VERSION
#define SOLARUS_MAJOR_VERSION 1
#endif

#ifndef SOLARUS_MINOR_VERSION
#define SOLARUS_MINOR_VERSION 6
#endif

#ifndef SOLARUS_PATCH_VERSION
#define SOLARUS_PATCH_VERSION 0
#endif
